apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-rollouts
helmCharts:
  - name: argo-rollouts
    releaseName: argo-rollouts
    namespace: argo-rollouts
    repo: https://argoproj.github.io/argo-helm
    version: 2.40.5
    valuesFile: values.yaml
resources:
  - httproute.yaml
  - namespace.yaml
