apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inspector
resources:
  - api-configmap.yaml
  - api-deployment.yaml
  - api-oidc.yaml
  - api-secrets.yaml
  - api-service.yaml
  - builder-cronjob.yaml
  - builder-secret.yaml
  - httproute.yaml
  - namespace.yaml
  - rbac.yaml
images:
  - name: ghcr.io/imdevinc/inspector-api
    newTag: v0.0.6
  - name: ghcr.io/imdevinc/inspector-builder
    newTag: v0.0.9
  - name: ghcr.io/imdevinc/inspector-session
    newTag: v0.0.8
