apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: btc-tracker
resources:
  - namespace.yaml
  - sealed.yaml
  - service.yaml
images:
  - name: thewilqq/btc-tracker
    newTag: v0.6.7
