apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: open-webui
    releaseName: openweb-ui
    namespace: open-webui
    repo: https://helm.openwebui.com
    version: 8.18.0
    valuesFile: values.yaml
namespace: open-webui
resources:
  - httproute.yaml
  - pvc.yaml
  - sealed.yaml
