apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: opentelemetry-operator
    releaseName: opentelemetry-operator
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.102.0
    valuesFile: values.yaml
    namespace: monitoring
resources:
  - alertmanager-creds.yaml
  - alertmanager.yaml
  - alerts.yaml
  - opentelemetry-collector.yaml
  - prometheus-operated.yaml
  - prometheus-operator.yaml
  - servicemonitors.yaml
namespace: monitoring
