manager:
  featureGatesMap:
    operator.targetallocator.mtls: true
  collectorImage:
    repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
admissionWebhooks:
  certManager:
    enabled: true
priorityClassName: important
