apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
helmCharts:
  - name: home-assistant
    releaseName: homeassistant
    namespace: homeassistant
    repo: https://k8s-at-home.com/charts
    version: 13.4.2
    valuesFile: values.yaml
resources:
  - esphome.yaml
  - sealed.yaml
  - zwave.yaml
images:
  - name: ghcr.io/home-assistant/home-assistant
    newTag: 2025.11.3
  - name: docker.io/zwavejs/zwave-js-ui
    newTag: 11.6.1
  - name: ghcr.io/esphome/esphome
    newTag: 2025.10.5
