apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwavejsui
  labels:
    app: zwavejsui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zwavejsui
  template:
    metadata:
      labels:
        app: zwavejsui
    spec:
      containers:
        - name: zwavejsui
          image: docker.io/zwavejs/zwave-js-ui
          imagePullPolicy: IfNotPresent
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8091
            timeoutSeconds: 1
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
            - name: websocket
              containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/store
              name: config
            - mountPath: /dev/zwave
              name: usb
          securityContext:
            privileged: true
      volumes:
        - hostPath:
            path: /mnt/media/config/zwavejsui
          name: config
        - hostPath:
            path: /dev/serial/by-id/usb-0658_0200-if00
          name: usb
---
apiVersion: v1
kind: Service
metadata:
  name: zwavejsui
  labels:
    app: zwavejsui
spec:
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: http
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: websocket
  selector:
    app: zwavejsui
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: zwavejsui
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - zwavejs.int.imdevinc.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: zwavejsui
          namespace: homeassistant
          port: 8091
