keybase:
  existingSecret: dawarich-creds

env:
  timeZone: "America/Los_Angeles"
  distanceUnit: mi
  railsEnv: production

dawarich:
  hosts:
    - dawarich.int.imdevinc.com
  resources:
    requests:
      cpu: 10m
      memory: 640Mi

sidekiq:
  resources:
    requests:
      cpu: 10m
      memory: 384Mi

postgresql:
  enabled: false
  host: postgres.postgres
  port: 5432
  auth:
    existingSecret: dawarich-creds

redis:
  enabled: false
  host: redis-master.redis
  port: 6379
  auth: false
