apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: comfyui
resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: comfyui
    newName: ghcr.io/imdevinc/comfyui
    newTag: sha-df90efe
replicas:
  - name: comfyui
    count: 1
