apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: couchdb
    releaseName: couchdb
    namespace: couchdb
    repo: https://apache.github.io/couchdb-helm
    version: 4.6.3
    valuesFile: values.yaml
namespace: couchdb
resources:
  - kubeseal.yaml
