apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: metallb
    releaseName: metallb
    namespace: metallb-system
    repo: https://metallb.github.io/metallb
    version: 0.15.3
    valuesFile: values.yaml
namespace: metallb-system
resources:
  - address-pool.yaml
