apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: nvidia-device-plugin
    releaseName: nvidia-device-plugin
    namespace: nvidia-device-plugin
    repo: https://nvidia.github.io/k8s-device-plugin
    version: 0.18.2
    valuesFile: values.yaml
namespace: nvidia-device-plugin
resources:
  - nfd.yaml
