apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hunyuan3d
resources:
  - manifest.yaml
  - sealed.yaml
images:
  - name: hunyuan3d:latest
    newName: ghcr.io/imdevinc/hunyuan3d
    newTag: sha-df90efe
