apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - prometheus-operator-crds
  - grafana-operator
  - kube-state-metrics
  - opentelemetry-operator
  - prometheus-node-exporter
  - victoria-metrics
