apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-rollouts-dashboard
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Management
    gethomepage.dev/icon: argo-cd.png
    gethomepage.dev/name: ArgoCD Rollouts
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
  hostnames:
  - argocd-rollouts.int.imdevinc.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: argo-rollouts-dashboard
      namespace: argo-cd
      port: 3100
