apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: crowdsec
    releaseName: crowdsec
    namespace: crowdsec
    repo: https://crowdsecurity.github.io/helm-charts
    version: 0.21.1
    valuesFile: values.yaml
namespace: crowdsec
resources:
  - sealed.yaml
