apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: dcgm-exporter
    releaseName: dcgm-exporter
    namespace: dcgm-exporter
    repo: https://nvidia.github.io/dcgm-exporter/helm-charts
    version: 4.7.1
namespace: dcgm-exporter
