apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kokoro
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: kokoro-web
    gethomepage.dev/name: kokoro
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
  hostnames:
  - kokoro.int.imdevinc.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: kokoro
      namespace: kokoro
      port: 3000

