apiVersion: v1
kind: Namespace
metadata:
  name: kokoro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kokoro
  labels:
    app: kokoro
    app.kubernetes.io/name: kokoro
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kokoro
      app.kubernetes.io/name: kokoro
  template:
    metadata:
      labels:
        app: kokoro
        app.kubernetes.io/name: kokoro
    spec:
      containers:
        - image: ghcr.io/eduardolat/kokoro-web
          imagePullPolicy: IfNotPresent
          name: kokoro
          env:
            - name: KW_PUBLIC_NO_TRACK
              value: "true"
            - name: ORIGIN
              value: https://kokoro.int.imdevinc.com
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - name: kokoro-cache
              mountPath: /kokoro/cache
      volumes:
        - name: kokoro-cache
          persistentVolumeClaim:
            claimName: kokoro-cache
---
apiVersion: v1
kind: Service
metadata:
  name: kokoro
  labels:
    app: kokoro
spec:
  selector:
    app: kokoro
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kokoro-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath-csi
