apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: grafana-operator
    releaseName: grafana-operator
    repo: https://grafana.github.io/helm-charts
    version: 5.21.4
    valuesFile: values.yaml
resources:
  - dashboards.yaml
  - grafana-creds.yaml
  - grafana-dashboard-urls.yaml
  - grafana-datasource.yaml
  - grafana.yaml
