apiVersion: v1
kind: Namespace
metadata:
  name: macro-track
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macro-track
  labels:
    app: macro-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: macro-track
  template:
    metadata:
      labels:
        app: macro-track
    spec:
      containers:
        - image: ghcr.io/imdevinc/macro-track-server
          imagePullPolicy: IfNotPresent
          name: macro-track
          envFrom:
            - secretRef:
                name: credentials
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: macro-track
  labels:
    app: macro-track
spec:
  selector:
    app: macro-track
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
