apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kube-state-metrics
    releaseName: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    version: 6.4.2
    valuesFile: values.yaml
