apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: job-ops
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - pvc.yaml
  - sealed.yaml
  - configmap.yaml
images:
  - name: ghcr.io/dakheera47/job-ops
    newTag: v0.1.14
