apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: scrutiny
    releaseName: scrutiny
    namespace: scrutiny
    repo: oci://tccr.io/truecharts
    version: 13.13.1
    valuesFile: values.yaml
namespace: scrutiny
resources:
  - httproute.yaml
