apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: scrutiny
  name: scrutiny
spec:
  ports:
    - name: main
      port: 10151
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: scrutiny
  type: ClusterIP
