apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rollouts-demo
  namespace: rollouts-demo
spec:
  hostnames:
    - rollouts-demo.int.imdevinc.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: traefik-gateway
      namespace: traefik
  rules:
    - backendRefs:
        - group: traefik.io
          kind: TraefikService
          name: bluegreen-demo
          namespace: rollouts-demo
      matches:
        - path:
            type: PathPrefix
            value: /
