apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: rollouts-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
        args:
          - name: service
            value: rollouts-demo-canary-rollout-8080@kubernetescrd
      canaryService: canary-rollout
      stableService: stable-rollout
      trafficRouting:
        traefik:
          weightedTraefikServiceName: bluegreen-demo
      steps:
        - setWeight: 20
        - pause: { duration: 5m }
        - setWeight: 40
        - pause: { duration: 5m }
        - setWeight: 60
        - pause: { duration: 5m }
        - setWeight: 80
        - pause: { duration: 5m }
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - image: argoproj/rollouts-demo:blue
          name: rollouts-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
