apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: rollouts-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    canary:
      canaryService: canary-rollout
      stableService: stable-rollout
      trafficRouting:
        traefik:
          weightedTraefikServiceName: bluegreen-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - image: argoproj/rollouts-demo:yellow
          name: rollouts-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
