apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: bluegreen-demo
  namespace: rollouts-demo
spec:
  weighted:
    services:
      - name: stable-rollout
        port: 8080
      - name: canary-rollout
        port: 8080
