apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rss-server
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: rss
    gethomepage.dev/name: RSS Server
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
  hostnames:
  - rss.int.imdevinc.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: rss-server
      namespace: rss-server
      port: 8080
