apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendarr
  labels:
    app: recommendarr
    app.kubernetes.io/name: recommendarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendarr
      app.kubernetes.io/name: recommendarr
  template:
    metadata:
      labels:
        app: recommendarr
        app.kubernetes.io/name: recommendarr
    spec:
      containers:
        - name: recommendarr
          env:
            - name: PUBLIC_URL
              value: https://recommendarr.int.imdevinc.com
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: recommendarr-secret
                  key: session-secret
            - name: CUSTOM_OAUTH_AUTH_URL
              value: https://login.int.imdevinc.com/authorize
            - name: CUSTOM_OAUTH_TOKEN_URL
              value: https://login.int.imdevinc.com/api/oidc/token
            - name: CUSTOM_OAUTH_USERINFO_URL
              value: https://login.int.imdevinc.com/api/oidc/userinfo
            - name: CUSTOM_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: recommendarr-secret
                  key: oidc-client-id
            - name: CUSTOM_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: recommendarr-secret
                  key: oidc-client-secret
          image: tannermiddleton/recommendarr:v1.4.4
          imagePullPolicy: IfNotPresent
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: mediaserver-volume
              mountPath: /app/server/data
              subPath: "config/recommendarr"
      volumes:
        - name: mediaserver-volume
          hostPath:
            path: /mnt/media
